server:
  port: 8761

eureka:
  server:
#    enable-self-preservation: false //关闭安全模式出来红色关闭提示字体
    renewal-percent-threshold: 0.0
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    healthcheck:
          enabled: true
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/



